apiVersion: v1
kind: Service
metadata:
  name: rustdesk-hbbs-service
  labels:
    {{- include "rustdesk-server.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.service.hbbs.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.service.hbbs.annotations }}
  {{- if not $.Values.service.annotations }}
  annotations:
  {{- end }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.portConfigs.hbbs.type }}
  {{- if and .Values.service.externalTrafficPolicy (or (eq .Values.portConfigs.hbbs.type "NodePort") (eq .Values.portConfigs.hbbs.type "LoadBalancer")) }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - name: "hbbs-nat-port"
      port: {{ .Values.portConfigs.hbbs.natPort.port }}
      protocol: TCP
      targetPort: 21115
    - name: "hbbs-registry-port"
      port: {{ .Values.portConfigs.hbbs.registryPort.port }}
      targetPort: 21116
      protocol: TCP
    - name: "hbbs-heartbeat-port"
      port: {{ .Values.portConfigs.hbbs.heartbeatPort.port }}
      protocol: UDP
      targetPort: 21116
    {{ if .Values.portConfigs.hbbs.webPort.enable }}
    - port: {{ .Values.portConfigs.hbbs.webPort.port }}
      targetPort: 21118
      protocol: TCP
      name: "hbbs-web-port"
    {{end}}
  selector:
    {{- include "rustdesk-server.selectorLabels" . | nindent 4 }}
